### ISSUE TITLE
É apenas uma sugestão e não um problema. Aliás seu vídeo é excelente. Brilhante didática.

### ISSUE THREAD

**Issue by jarbelix** [ciceromartins/conceitos-basicos-python#1]
Na linha 20 você poderia escrever assim:
`print("Erro ao acessar a chave escolhida!", e)`
que o erro da chave seria mostrada também.

**Comment by ciceromartins** [comment]
Com certeza poderia!
Porém no exemplo, como a chave é estática, não tinha por que ser redundante, já que o cara sabe qual chave ele acessou.

Agora quando você tem múltiplos acessos dentro do bloco de código, sem dúvida faz muito sentido especificar!
